My Project: Arduino_ADConverter/Arduino_ADConverter.ino File Reference
Arduino_ADConverter.ino File Reference
#include <SPI.h>
#include "AD7193.h"
Macros
#define AD7193_RDY_STATE MOSI
#define PMOD1_CS_PIN SS
#define PMOD1_CS_LOW digitalWrite(SS,LOW);
#define PMOD1_CS_HIGH digitalWrite(SS,HIGH);
#define AD7193_CH_0 0
#define AD7193_CH_1 1
#define AD7193_CH_2 2
#define AD7193_CH_3 3
#define AD7193_CH_4 4
#define AD7193_CH_5 5
#define AD7193_CH_6 6
#define AD7193_CH_7 7
#define AD7193_CH_8 8
Functions
unsigned char AD7193_Init (void)
void AD7193_SetRegisterValue (unsigned char registerAddress, unsigned long registerValue, unsigned char bytesNumber, unsigned char modifyCS)
unsigned long AD7193_GetRegisterValue (unsigned char registerAddress, unsigned char bytesNumber, unsigned char modifyCS)
void AD7193_SetMode (unsigned char mode)
void AD7193_Reset (void)
void AD7193_SetPower (unsigned char pwrMode)
void AD7193_WaitRdyGoLow (void)
void AD7193_ChannelSelect (unsigned short channel)
void AD7193_Calibrate (unsigned char mode, unsigned char channel)
void AD7193_RangeSetup (unsigned char polarity, unsigned char range)
unsigned long AD7193_SingleConversion (void)
unsigned long AD7193_ContinuousReadAvg (unsigned char sampleNumber)
unsigned long AD7193_TemperatureRead (void)
float AD7193_ConvertToVolts (unsigned long rawData, float vRef)
void setup ()
void loop ()
Variables
unsigned char currentPolarity = 1
unsigned char currentGain = 0
Macro Definition Documentation
#define AD7193_CH_0 0
Definition at line 9 of file Arduino_ADConverter.ino.
Referenced by setup().
#define AD7193_CH_1 1
Definition at line 10 of file Arduino_ADConverter.ino.
#define AD7193_CH_2 2
Definition at line 11 of file Arduino_ADConverter.ino.
#define AD7193_CH_3 3
Definition at line 12 of file Arduino_ADConverter.ino.
#define AD7193_CH_4 4
Definition at line 13 of file Arduino_ADConverter.ino.
#define AD7193_CH_5 5
Definition at line 14 of file Arduino_ADConverter.ino.
#define AD7193_CH_6 6
Definition at line 15 of file Arduino_ADConverter.ino.
#define AD7193_CH_7 7
Definition at line 16 of file Arduino_ADConverter.ino.
#define AD7193_CH_8 8
Definition at line 17 of file Arduino_ADConverter.ino.
#define AD7193_RDY_STATE MOSI
Definition at line 3 of file Arduino_ADConverter.ino.
Referenced by AD7193_WaitRdyGoLow().
#define PMOD1_CS_HIGH digitalWrite(SS,HIGH);
Definition at line 6 of file Arduino_ADConverter.ino.
Referenced by AD7193_Calibrate(), AD7193_ContinuousReadAvg(), and AD7193_SingleConversion().
#define PMOD1_CS_LOW digitalWrite(SS,LOW);
Definition at line 5 of file Arduino_ADConverter.ino.
Referenced by AD7193_Calibrate(), AD7193_ContinuousReadAvg(), and AD7193_SingleConversion().
#define PMOD1_CS_PIN SS
Definition at line 4 of file Arduino_ADConverter.ino.
Referenced by AD7193_GetRegisterValue(), and AD7193_SetRegisterValue().
Function Documentation
void AD7193_Calibrate (unsigned char mode, unsigned char channel)
Performs the given calibration to the specified channel.
Definition at line 166 of file Arduino_ADConverter.ino.
void AD7193_ChannelSelect (unsigned short channel)
Selects the channel to be enabled.
Definition at line 151 of file Arduino_ADConverter.ino.
unsigned long AD7193_ContinuousReadAvg (unsigned char sampleNumber)
Returns the average of several conversion results.
Definition at line 231 of file Arduino_ADConverter.ino.
float AD7193_ConvertToVolts (unsigned long rawData, float vRef)
Converts 24-bit raw data to volts.
Definition at line 269 of file Arduino_ADConverter.ino.
unsigned long AD7193_GetRegisterValue (unsigned char registerAddress, unsigned char bytesNumber, unsigned char modifyCS)
Reads the value of a register.
Definition at line 73 of file Arduino_ADConverter.ino.
unsigned char AD7193_Init (void)
Checks if the AD7139 part is present.
Initialize SPI communication.
Definition at line 23 of file Arduino_ADConverter.ino.
void AD7193_RangeSetup (unsigned char polarity, unsigned char range)
Selects the polarity of the conversion and the ADC input range.
Definition at line 185 of file Arduino_ADConverter.ino.
void AD7193_Reset (void)
Resets the device.
Definition at line 116 of file Arduino_ADConverter.ino.
void AD7193_SetMode (unsigned char mode)
Selects the AD7193's operating mode.
Definition at line 104 of file Arduino_ADConverter.ino.
References AD7193_GetRegisterValue(), AD7193_MODE_SEL, AD7193_REG_MODE, and AD7193_SetRegisterValue().
void AD7193_SetPower (unsigned char pwrMode)
Set device to idle or power-down.
Definition at line 127 of file Arduino_ADConverter.ino.
void AD7193_SetRegisterValue (unsigned char registerAddress, unsigned long registerValue, unsigned char bytesNumber, unsigned char modifyCS)
Writes data into a register.
Definition at line 41 of file Arduino_ADConverter.ino.
unsigned long AD7193_SingleConversion (void)
Returns the result of a single conversion.
Definition at line 209 of file Arduino_ADConverter.ino.
unsigned long AD7193_TemperatureRead (void)
Read data from temperature sensor and converts it to Celsius degrees.
Definition at line 255 of file Arduino_ADConverter.ino.
void AD7193_WaitRdyGoLow (void)
Waits for RDY pin to go low.
Definition at line 144 of file Arduino_ADConverter.ino.
void loop ()
Definition at line 318 of file Arduino_ADConverter.ino.
References AD7193_ContinuousReadAvg(), and AD7193_ConvertToVolts().
void setup ()
Resets the device.
Select Channel 0
Calibrates channel 0.
Selects unipolar operation and ADC's input range to +-2.5V.
Definition at line 283 of file Arduino_ADConverter.ino.
References AD7193_Calibrate(), AD7193_CH_0, AD7193_ChannelSelect(), AD7193_CONF_GAIN_1, AD7193_CONF_PSEUDO, AD7193_GetRegisterValue(), AD7193_Init(), AD7193_MODE_CAL_INT_ZERO, AD7193_RangeSetup(), AD7193_REG_CONF, AD7193_Reset(), and AD7193_SetRegisterValue().
Variable Documentation
unsigned char currentGain = 0
Definition at line 20 of file Arduino_ADConverter.ino.
Referenced by AD7193_ConvertToVolts(), and AD7193_RangeSetup().
unsigned char currentPolarity = 1
Definition at line 19 of file Arduino_ADConverter.ino.
Referenced by AD7193_ConvertToVolts(), and AD7193_RangeSetup().