My Project: /home/coudert/lml/stage/IG2I/Robin/ADConverter/ArduinoDUE_ADConverter/ArduinoDUE_ADConverter.ino File Reference
ArduinoDUE_ADConverter.ino File Reference
#include <SPI.h>
#include "AD7193.h"
Macros
#define AD7193_RDY_STATE MOSI
#define PMOD1_CS_PIN 10
#define PMOD1_CS_LOW digitalWrite(PMOD1_CS_PIN,LOW);
#define PMOD1_CS_HIGH digitalWrite(PMOD1_CS_PIN,HIGH);
#define AD7193_CH_0 0
Functions
unsigned char AD7193_Init (void)
void AD7193_SetRegisterValue (unsigned char registerAddress, unsigned long registerValue, unsigned char bytesNumber, unsigned char modifyCS)
unsigned long AD7193_GetRegisterValue (unsigned char registerAddress, unsigned char bytesNumber, unsigned char modifyCS)
void AD7193_SetMode (unsigned char mode)
void AD7193_Reset (void)
void AD7193_SetPower (unsigned char pwrMode)
void AD7193_WaitRdyGoLow (void)
void AD7193_ChannelSelect (unsigned short channel)
void AD7193_Calibrate (unsigned char mode, unsigned char channel)
void AD7193_RangeSetup (unsigned char polarity, unsigned char range)
unsigned long AD7193_SingleConversion (void)
unsigned long AD7193_ContinuousReadAvg (unsigned char sampleNumber)
unsigned long AD7193_TemperatureRead (void)
float AD7193_ConvertToVolts (unsigned long rawData, float vRef)
void setup ()
void loop ()
Variables
unsigned char currentPolarity = 1
unsigned char currentGain = 0
Macro Definition Documentation
#define AD7193_CH_0 0
Definition at line 7 of file ArduinoDUE_ADConverter.ino.
Referenced by setup().
#define AD7193_RDY_STATE MOSI
Definition at line 3 of file ArduinoDUE_ADConverter.ino.
Referenced by AD7193_WaitRdyGoLow().
#define PMOD1_CS_HIGH digitalWrite(PMOD1_CS_PIN,HIGH);
Definition at line 6 of file ArduinoDUE_ADConverter.ino.
Referenced by AD7193_Calibrate(), AD7193_ContinuousReadAvg(), and AD7193_SingleConversion().
#define PMOD1_CS_LOW digitalWrite(PMOD1_CS_PIN,LOW);
Definition at line 5 of file ArduinoDUE_ADConverter.ino.
Referenced by AD7193_Calibrate(), AD7193_ContinuousReadAvg(), and AD7193_SingleConversion().
#define PMOD1_CS_PIN 10
Definition at line 4 of file ArduinoDUE_ADConverter.ino.
Referenced by AD7193_GetRegisterValue(), AD7193_Init(), AD7193_Reset(), and AD7193_SetRegisterValue().
Function Documentation
void AD7193_Calibrate (unsigned char mode, unsigned char channel)
Performs the given calibration to the specified channel.
Definition at line 145 of file ArduinoDUE_ADConverter.ino.
References AD7193_ChannelSelect(), AD7193_GetRegisterValue(), AD7193_MODE_SEL, AD7193_REG_MODE, AD7193_SetRegisterValue(), AD7193_WaitRdyGoLow(), PMOD1_CS_HIGH, and PMOD1_CS_LOW.
void AD7193_ChannelSelect (unsigned short channel)
Selects the channel to be enabled.
Definition at line 131 of file ArduinoDUE_ADConverter.ino.
References AD7193_CONF_CHAN, AD7193_GetRegisterValue(), AD7193_REG_CONF, and AD7193_SetRegisterValue().
unsigned long AD7193_ContinuousReadAvg (unsigned char sampleNumber)
Returns the average of several conversion results.
Definition at line 204 of file ArduinoDUE_ADConverter.ino.
References AD7193_CLK_INT, AD7193_GetRegisterValue(), AD7193_MODE_CLKSRC, AD7193_MODE_CONT, AD7193_MODE_RATE, AD7193_MODE_SEL, AD7193_REG_DATA, AD7193_REG_MODE, AD7193_SetRegisterValue(), AD7193_WaitRdyGoLow(), PMOD1_CS_HIGH, and PMOD1_CS_LOW.
float AD7193_ConvertToVolts (unsigned long rawData, float vRef)
Converts 24-bit raw data to volts.
Definition at line 238 of file ArduinoDUE_ADConverter.ino.
References currentGain, and currentPolarity.
unsigned long AD7193_GetRegisterValue (unsigned char registerAddress, unsigned char bytesNumber, unsigned char modifyCS)
Reads the value of a register.
Definition at line 59 of file ArduinoDUE_ADConverter.ino.
References AD7193_COMM_ADDR, AD7193_COMM_READ, and PMOD1_CS_PIN.
unsigned char AD7193_Init (void)
Checks if the AD7139 part is present.
Initialize SPI communication.
Definition at line 11 of file ArduinoDUE_ADConverter.ino.
References AD7193_GetRegisterValue(), AD7193_ID_MASK, AD7193_REG_ID, AD7193_Reset(), ID_AD7193, and PMOD1_CS_PIN.
void AD7193_RangeSetup (unsigned char polarity, unsigned char range)
Selects the polarity of the conversion and the ADC input range.
Definition at line 162 of file ArduinoDUE_ADConverter.ino.
References AD7193_CONF_GAIN, AD7193_CONF_UNIPOLAR, AD7193_GetRegisterValue(), AD7193_REG_CONF, AD7193_SetRegisterValue(), currentGain, and currentPolarity.
void AD7193_Reset (void)
Resets the device.
Definition at line 100 of file ArduinoDUE_ADConverter.ino.
References PMOD1_CS_PIN.
void AD7193_SetMode (unsigned char mode)
Definition at line 89 of file ArduinoDUE_ADConverter.ino.
References AD7193_GetRegisterValue(), AD7193_MODE_SEL, AD7193_REG_MODE, and AD7193_SetRegisterValue().
void AD7193_SetPower (unsigned char pwrMode)
Set device to idle or power-down.
Definition at line 109 of file ArduinoDUE_ADConverter.ino.
References AD7193_GetRegisterValue(), AD7193_MODE_IDLE, AD7193_MODE_PWRDN, AD7193_MODE_SEL, AD7193_REG_MODE, and AD7193_SetRegisterValue().
void AD7193_SetRegisterValue (unsigned char registerAddress, unsigned long registerValue, unsigned char bytesNumber, unsigned char modifyCS)
Writes data into a register.
Definition at line 29 of file ArduinoDUE_ADConverter.ino.
References AD7193_COMM_ADDR, AD7193_COMM_WRITE, and PMOD1_CS_PIN.
unsigned long AD7193_SingleConversion (void)
Returns the result of a single conversion.
Definition at line 184 of file ArduinoDUE_ADConverter.ino.
References AD7193_CLK_INT, AD7193_GetRegisterValue(), AD7193_MODE_CLKSRC, AD7193_MODE_RATE, AD7193_MODE_SEL, AD7193_MODE_SINGLE, AD7193_REG_DATA, AD7193_REG_MODE, AD7193_SetRegisterValue(), AD7193_WaitRdyGoLow(), PMOD1_CS_HIGH, and PMOD1_CS_LOW.
unsigned long AD7193_TemperatureRead (void)
Read data from temperature sensor and converts it to Celsius degrees.
Definition at line 225 of file ArduinoDUE_ADConverter.ino.
References AD7193_CH_TEMP, AD7193_ChannelSelect(), AD7193_CONF_GAIN_1, AD7193_RangeSetup(), and AD7193_SingleConversion().
void AD7193_WaitRdyGoLow (void)
Waits for RDY pin to go low.
Definition at line 125 of file ArduinoDUE_ADConverter.ino.
References AD7193_RDY_STATE.
void loop ()
Definition at line 287 of file ArduinoDUE_ADConverter.ino.
References AD7193_ConvertToVolts(), and AD7193_SingleConversion().
void setup ()
Resets the device.
Select Channel 0
Calibrates channel 0.
Selects unipolar operation and ADC's input range to +-2.5V.
Definition at line 252 of file ArduinoDUE_ADConverter.ino.
References AD7193_Calibrate(), AD7193_CH_0, AD7193_ChannelSelect(), AD7193_CONF_GAIN_1, AD7193_CONF_PSEUDO, AD7193_GetRegisterValue(), AD7193_Init(), AD7193_MODE_CAL_INT_ZERO, AD7193_RangeSetup(), AD7193_REG_CONF, AD7193_Reset(), and AD7193_SetRegisterValue().
Variable Documentation
unsigned char currentGain = 0
Definition at line 9 of file ArduinoDUE_ADConverter.ino.
unsigned char currentPolarity = 1
Definition at line 8 of file ArduinoDUE_ADConverter.ino.