My Project: /home/coudert/lml/stage/IG2I/Robin/ADConverter/MX3cK_ADConverter/MX3cK_ADConverter.pde File Reference
MX3cK_ADConverter.pde File Reference
#include "AD7193.h"
Macros
#define AD7193_RDY_STATE MOSI
#define PMOD1_CS_PIN SS
#define PMOD1_CS_LOW digitalWrite(SS,LOW);
#define PMOD1_CS_HIGH digitalWrite(SS,HIGH);
#define AD7193_CH_0 0
#define AD7193_CH_1 1
#define AD7193_CH_2 2
#define AD7193_CH_3 3
#define AD7193_CH_4 4
#define AD7193_CH_5 5
#define AD7193_CH_6 6
#define AD7193_CH_7 7
#define AD7193_CH_8 8
Functions
unsigned char AD7193_Init (void)
void AD7193_SetRegisterValue (unsigned char registerAddress, unsigned long registerValue, unsigned char bytesNumber, unsigned char modifyCS)
unsigned long AD7193_GetRegisterValue (unsigned char registerAddress, unsigned char bytesNumber, unsigned char modifyCS)
void AD7193_SetMode (unsigned char mode)
void AD7193_Reset (void)
void AD7193_SetPower (unsigned char pwrMode)
void AD7193_WaitRdyGoLow (void)
void AD7193_ChannelSelect (unsigned short channel)
void AD7193_Calibrate (unsigned char mode, unsigned char channel)
void AD7193_RangeSetup (unsigned char polarity, unsigned char range)
unsigned long AD7193_SingleConversion (void)
unsigned long AD7193_ContinuousReadAvg (unsigned char sampleNumber)
unsigned long AD7193_TemperatureRead (void)
float AD7193_ConvertToVolts (unsigned long rawData, float vRef)
unsigned char SPI_Init (unsigned char lsbFirst, unsigned long clockFreq, unsigned char clockPol, unsigned char clockEdg)
unsigned char SPI_Read (unsigned char slaveDeviceId, unsigned char *data, unsigned char bytesNumber)
unsigned char SPI_Write (unsigned char slaveDeviceId, unsigned char *data, unsigned char bytesNumber)
void setup ()
void loop ()
Variables
unsigned char currentPolarity = 1
unsigned char currentGain = 0
Macro Definition Documentation
#define AD7193_CH_0 0
Definition at line 8 of file MX3cK_ADConverter.pde.
Referenced by setup().
#define AD7193_CH_1 1
Definition at line 9 of file MX3cK_ADConverter.pde.
#define AD7193_CH_2 2
Definition at line 10 of file MX3cK_ADConverter.pde.
#define AD7193_CH_3 3
Definition at line 11 of file MX3cK_ADConverter.pde.
#define AD7193_CH_4 4
Definition at line 12 of file MX3cK_ADConverter.pde.
#define AD7193_CH_5 5
Definition at line 13 of file MX3cK_ADConverter.pde.
#define AD7193_CH_6 6
Definition at line 14 of file MX3cK_ADConverter.pde.
#define AD7193_CH_7 7
Definition at line 15 of file MX3cK_ADConverter.pde.
#define AD7193_CH_8 8
Definition at line 16 of file MX3cK_ADConverter.pde.
#define AD7193_RDY_STATE MOSI
Definition at line 2 of file MX3cK_ADConverter.pde.
Referenced by AD7193_WaitRdyGoLow().
#define PMOD1_CS_HIGH digitalWrite(SS,HIGH);
Definition at line 5 of file MX3cK_ADConverter.pde.
Referenced by AD7193_Calibrate(), AD7193_ContinuousReadAvg(), and AD7193_SingleConversion().
#define PMOD1_CS_LOW digitalWrite(SS,LOW);
Definition at line 4 of file MX3cK_ADConverter.pde.
Referenced by AD7193_Calibrate(), AD7193_ContinuousReadAvg(), and AD7193_SingleConversion().
#define PMOD1_CS_PIN SS
Definition at line 3 of file MX3cK_ADConverter.pde.
Function Documentation
void AD7193_Calibrate (unsigned char mode, unsigned char channel)
Performs the given calibration to the specified channel.
Definition at line 152 of file MX3cK_ADConverter.pde.
References AD7193_ChannelSelect(), AD7193_GetRegisterValue(), AD7193_MODE_SEL, AD7193_REG_MODE, AD7193_SetRegisterValue(), AD7193_WaitRdyGoLow(), PMOD1_CS_HIGH, and PMOD1_CS_LOW.
Referenced by setup().
void AD7193_ChannelSelect (unsigned short channel)
Selects the channel to be enabled.
Definition at line 137 of file MX3cK_ADConverter.pde.
References AD7193_CONF_CHAN, AD7193_GetRegisterValue(), AD7193_REG_CONF, and AD7193_SetRegisterValue().
Referenced by AD7193_Calibrate(), AD7193_TemperatureRead(), and setup().
unsigned long AD7193_ContinuousReadAvg (unsigned char sampleNumber)
Returns the average of several conversion results.
Definition at line 214 of file MX3cK_ADConverter.pde.
References AD7193_CLK_INT, AD7193_GetRegisterValue(), AD7193_MODE_CLKSRC, AD7193_MODE_CONT, AD7193_MODE_RATE, AD7193_MODE_SEL, AD7193_REG_DATA, AD7193_REG_MODE, AD7193_SetRegisterValue(), AD7193_WaitRdyGoLow(), PMOD1_CS_HIGH, and PMOD1_CS_LOW.
Referenced by loop().
float AD7193_ConvertToVolts (unsigned long rawData, float vRef)
Converts 24-bit raw data to volts.
Definition at line 254 of file MX3cK_ADConverter.pde.
References currentGain, and currentPolarity.
Referenced by loop().
unsigned long AD7193_GetRegisterValue (unsigned char registerAddress, unsigned char bytesNumber, unsigned char modifyCS)
Reads the value of a register.
Definition at line 64 of file MX3cK_ADConverter.pde.
References AD7193_COMM_ADDR, AD7193_COMM_READ, AD7193_SLAVE_ID, PMOD1_CS_PIN, and SPI_Read().
Referenced by AD7193_Calibrate(), AD7193_ChannelSelect(), AD7193_ContinuousReadAvg(), AD7193_Init(), AD7193_RangeSetup(), AD7193_SetMode(), AD7193_SetPower(), AD7193_SingleConversion(), and setup().
unsigned char AD7193_Init (void)
Checks if the AD7139 part is present.
Initialize SPI communication.
Initialize SPI communication.
Definition at line 23 of file MX3cK_ADConverter.pde.
References AD7193_GetRegisterValue(), AD7193_ID_MASK, AD7193_REG_ID, AD7193_Reset(), ID_AD7193, and SPI_Init().
Referenced by setup().
void AD7193_RangeSetup (unsigned char polarity, unsigned char range)
Selects the polarity of the conversion and the ADC input range.
Definition at line 171 of file MX3cK_ADConverter.pde.
References AD7193_CONF_GAIN, AD7193_CONF_UNIPOLAR, AD7193_GetRegisterValue(), AD7193_REG_CONF, AD7193_SetRegisterValue(), currentGain, and currentPolarity.
Referenced by AD7193_TemperatureRead(), and setup().
void AD7193_Reset (void)
Resets the device.
Definition at line 98 of file MX3cK_ADConverter.pde.
References AD7193_SLAVE_ID, and SPI_Write().
Referenced by AD7193_Init(), and setup().
void AD7193_SetMode (unsigned char mode)
Selects the AD7193's operating mode.
Definition at line 86 of file MX3cK_ADConverter.pde.
References AD7193_GetRegisterValue(), AD7193_MODE_SEL, AD7193_REG_MODE, and AD7193_SetRegisterValue().
void AD7193_SetPower (unsigned char pwrMode)
Set device to idle or power-down.
Definition at line 113 of file MX3cK_ADConverter.pde.
References AD7193_GetRegisterValue(), AD7193_MODE_IDLE, AD7193_MODE_PWRDN, AD7193_MODE_SEL, AD7193_REG_MODE, and AD7193_SetRegisterValue().
void AD7193_SetRegisterValue (unsigned char registerAddress, unsigned long registerValue, unsigned char bytesNumber, unsigned char modifyCS)
Writes data into a register.
Definition at line 41 of file MX3cK_ADConverter.pde.
References AD7193_COMM_ADDR, AD7193_COMM_WRITE, AD7193_SLAVE_ID, PMOD1_CS_PIN, and SPI_Write().
Referenced by AD7193_Calibrate(), AD7193_ChannelSelect(), AD7193_ContinuousReadAvg(), AD7193_RangeSetup(), AD7193_SetMode(), AD7193_SetPower(), AD7193_SingleConversion(), and setup().
unsigned long AD7193_SingleConversion (void)
Returns the result of a single conversion.
Definition at line 193 of file MX3cK_ADConverter.pde.
References AD7193_CLK_INT, AD7193_GetRegisterValue(), AD7193_MODE_CLKSRC, AD7193_MODE_RATE, AD7193_MODE_SEL, AD7193_MODE_SINGLE, AD7193_REG_DATA, AD7193_REG_MODE, AD7193_SetRegisterValue(), AD7193_WaitRdyGoLow(), PMOD1_CS_HIGH, and PMOD1_CS_LOW.
Referenced by AD7193_TemperatureRead(), and loop().
unsigned long AD7193_TemperatureRead (void)
Read data from temperature sensor and converts it to Celsius degrees.
Definition at line 238 of file MX3cK_ADConverter.pde.
References AD7193_CH_TEMP, AD7193_ChannelSelect(), AD7193_CONF_GAIN_1, AD7193_RangeSetup(), and AD7193_SingleConversion().
void AD7193_WaitRdyGoLow (void)
Waits for RDY pin to go low.
Definition at line 130 of file MX3cK_ADConverter.pde.
References AD7193_RDY_STATE.
Referenced by AD7193_Calibrate(), AD7193_ContinuousReadAvg(), and AD7193_SingleConversion().
void loop ()
Definition at line 385 of file MX3cK_ADConverter.pde.
References AD7193_ContinuousReadAvg(), and AD7193_ConvertToVolts().
void setup ()
Resets the device.
Select Channel 0
Calibrates channel 0.
Selects unipolar operation and ADC's input range to +-2.5V.
Definition at line 349 of file MX3cK_ADConverter.pde.
References AD7193_Calibrate(), AD7193_CH_0, AD7193_ChannelSelect(), AD7193_CONF_GAIN_1, AD7193_CONF_PSEUDO, AD7193_GetRegisterValue(), AD7193_Init(), AD7193_MODE_CAL_INT_ZERO, AD7193_RangeSetup(), AD7193_REG_CONF, AD7193_Reset(), and AD7193_SetRegisterValue().
unsigned char SPI_Init (unsigned char lsbFirst, unsigned long clockFreq, unsigned char clockPol, unsigned char clockEdg)
< Initializes the SPI communication peripheral. Writes data to SPI.
< Fsck = Fpb / (2 * (SPIxBRG + 1))
< Clear the content of SPI2CON register
< SPI Clock Edge Select bit
< Clock Polarity Select bit
< Enable master mode
< Enable SPI peripheral
Definition at line 269 of file MX3cK_ADConverter.pde.
Referenced by AD7193_Init().
unsigned char SPI_Read (unsigned char slaveDeviceId, unsigned char * data, unsigned char bytesNumber)
Definition at line 292 of file MX3cK_ADConverter.pde.
Referenced by AD7193_GetRegisterValue().
unsigned char SPI_Write (unsigned char slaveDeviceId, unsigned char * data, unsigned char bytesNumber)
Reads data from SPI.
Definition at line 323 of file MX3cK_ADConverter.pde.
Referenced by AD7193_Reset(), and AD7193_SetRegisterValue().
Variable Documentation
unsigned char currentGain = 0
Definition at line 19 of file MX3cK_ADConverter.pde.
unsigned char currentPolarity = 1
Definition at line 18 of file MX3cK_ADConverter.pde.